app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('menu/', views.menu, name='menu'),
    path('charts/', views.charts, name='charts'),
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('register/', views.register, name='register'),
    path('registrar/', views.registrar, name='registrar'),
    path('autenticar/', views.autenticar, name='autenticar'),    
    path('logout/', views.view_logout, name='view_logout'),
    path('seeProyect/', views.seeProyect, name='seeProyect'),
    path('saveProyect/', views.saveProyect, name='saveProyect'),
    path('editProyect/', views.editProyect, name='editProyect'),
    path('EditEstado/', views.EditEstado, name='EditEstado'),
    path('EditTask/', views.EditTask, name='EditTask'),
    path('seeTask/', views.seeTask, name='seeTask'),
    path('addDeveloper/', views.addDeveloper, name='addDeveloper'),
    path('listdeveloper/', views.listdeveloper, name='listdeveloper'),
    path('addTarea/', views.addTarea, name='addTarea'),
    path('404/', views.notfound, name='404'),
    path('listdeveloper/eliminar/<int:id>/', views.view_eliminar_developer, name='view_eliminar_developer'),
    path('listtask/eliminar/<int:id>/', views.view_remove_developer, name='view_remove_developer'),
    path('listdeveloper/habilitar/<int:id>/', views.view_habilitar_developer, name='view_habilitar_developer'),
    path('listcoment/see/<int:id>/', views.view_see_developer, name='view_see_developer'),
    path('addComent/', views.addComent, name='addComent'),
]

app/templates/app/Index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TFS - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'app/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                    {% if messages %}
                        {% for message in messages %}
                          <div class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{message.tags}}{%endif%} alert-dismissible fade show" role="alert">
                              {{message}}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        {% endfor %}
                    {% endif %}
                  </div>
                  <form class="user needs-validation" action="{% url 'app:autenticar' %}" method="POST" novalidate>
                     {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleUsuario" name="Username" placeholder="Usuario" required>
                      <div class="valid-feedback"></div>
                      <div class="invalid-feedback">Please choose a Usuario.</div>
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="exampleInputPassword" name="Password" placeholder="Password" required>
                      <div class="valid-feedback"></div>
                      <div class="invalid-feedback">Please choose a Password.</div>
                    </div>
                    <div class="form-group">
                      <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="CustomSelect" required>
                        <option value="" selected>select rol</option>
                        <option value="Developer">Developer</option>
                        <option value="productowner">Product Owner</option>
                      </select>
                      <div class="invalid-feedback">invalid rol selection</div>
                    </div>
                    <button class="btn btn-primary btn-user btn-block" type="submit">
                      Login
                    </button>               
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'app:register' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src=" {% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src=" {% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src=" {% static 'app/js/sb-admin-2.min.js' %}"></script>
<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
</body>

</html>

app/templates/app/charts.html
{% extends "app/base.html" %}
{% load static %}

{% block titulo %}
TFS - Menu
{% endblock %}

{% block contenido %}
<h1 class="h3 mb-2 text-gray-800">Charts</h1>
<p class="mb-4">Chart.js is a third party plugin that is used to generate the charts in this theme. The charts below have been customized - for further customization options, please visit the <a target="_blank" href="https://www.chartjs.org/docs/latest/">official Chart.js documentation</a>.</p>

<!-- Content Row -->
<div class="row">

  <div class="col-xl-8 col-lg-7">

    <!-- Area Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
      </div>
      <div class="card-body">
        <div class="chart-area">
          <canvas id="myAreaChart"></canvas>
        </div>
        <hr>
        Styling for the area chart can be found in the <code>/js/demo/chart-area-demo.js</code> file.
      </div>
    </div>

    <!-- Bar Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
      </div>
      <div class="card-body">
        <div class="chart-bar">
          <canvas id="myBarChart"></canvas>
        </div>
        <hr>
        Styling for the bar chart can be found in the <code>/js/demo/chart-bar-demo.js</code> file.
      </div>
    </div>

  </div>

  <!-- Donut Chart -->
  <div class="col-xl-4 col-lg-5">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-pie pt-4">
          <canvas id="myPieChart"></canvas>
        </div>
        <hr>
        Styling for the donut chart can be found in the <code>/js/demo/chart-pie-demo.js</code> file.
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/app/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Forgot Password</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'app/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                  </div>
                  <form class="user needs-validation" novalidate>
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address..." required>
                      <div class="valid-feedback"></div>
                      <div class="invalid-feedback">Please choose a Email.</div>
                    </div>
                    <button class="btn btn-primary btn-user btn-block" type="submit">
                      Reset Password
                    </button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'app:register' %}">Create an Account!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'app:index' %}">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'app/js/sb-admin-2.min.js' %}"></script>

  <script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
      'use strict';
      window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
          form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
              event.preventDefault();
              event.stopPropagation();
            }
            form.classList.add('was-validated');
          }, false);
        });
      }, false);
    })();
  </script>
</body>

</html>

app/templates/app/listdeveloper.html
{% extends "app/base.html" %}
{% load static %}

{% block titulo %}
TFS - Menu
{% endblock %}

{% block contenido %}

<div class="row">
    <div class="col-sm-4">
        <h1 class="h3 mb-4 text-gray-800">List Developer</h1>
    </div>
    <div class="col-sm-8">
        <button class="btn btn-primary float-right"  data-toggle="modal" data-target="#exampleModalScrollableNewDeve"><svg class="bi bi-plus-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
          <path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"/>
          <path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
        </svg> Add
      </button>
    </div>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">homework progress</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>Developer</th>
                <th>Proyect</th>
                <th>State</th>
                <th class="text-center">Action</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th>Developer</th>
                <th>Proyect</th>
                <th>State</th>
                <th class="text-center">Action</th>
            </tr>
            </tfoot>
            <tbody>
            {% for u in lista_user %}
              {% for d in lista_developers %}
                  {%if d.usuario_id == u.id %}
                      {% if u.id != request.user.id %}
                          {% for p in lista_proyecto %}
                              {% if d.proyecto_id == p.id%}
                              <tr>
                                  <td>{{u.first_name}}&nbsp;{{u.last_name}}</td>
                                  <td>{{p.nombre}}</td>
                                  <td>{%if d.activo == 1%} <span class="badge badge-success">Activo</span>{%else%}<span class="badge badge-danger">Deshabilitado</span>{%endif%}</td>
                                  <td class="text-center"> {%if d.activo == 0%}<a class="btn btn-success" href="{% url 'app:view_habilitar_developer' d.id %}"><svg class="bi bi-file-check" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M9 1H4a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V8h-1v5a1 1 0 01-1 1H4a1 1 0 01-1-1V3a1 1 0 011-1h5V1z"/>
                                      <path fill-rule="evenodd" d="M15.854 2.146a.5.5 0 010 .708l-3 3a.5.5 0 01-.708 0l-1.5-1.5a.5.5 0 01.708-.708L12.5 4.793l2.646-2.647a.5.5 0 01.708 0z" clip-rule="evenodd"/>
                                      </svg></a> {% else %}<a class="btn btn-danger" href="{% url 'app:view_eliminar_developer' d.id %}"><svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
                                  </svg>
                                  </a>{%endif%}</td>
                              </tr>
                              {%endif%}
                          {% endfor %}
                      {%endif%}
                  {%endif%}
              {% endfor %}
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>

<!--agrgar developer-->
<div class="modal fade" id="exampleModalScrollableNewDeve" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Add Developer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="needs-validation" action="{% url 'app:addDeveloper' %}" method="post" novalidate>
      {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <select class="custom-select mr-sm-2" id="CustomSelectproyect" name="CustomSelectproyect" required>
              <option value="" selected>select Proyecto</option>
              {% for p in lista_proyecto %}
                <option value="{{p.id}}">{{p.nombre}}</option>
              {% endfor %}
            </select>
            <div class="invalid-feedback">invalid proyect selection</div>
          </div>
          <div class="form-group">
            <select class="custom-select mr-sm-2" id="CustomSelectdeveloper" name="CustomSelectdeveloper" >
              <option value="" selected>select Developer</option>
              {% for u in lista_user %}
                {% if u.id != request.user.id %}
                  <option value="{{u.id}}">{{u.first_name}}&nbsp;{{u.last_name}}</option>
                  {%endif%}
              {% endfor %}
            </select>
            <div class="invalid-feedback">invalid developer selection</div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div> 

{% endblock %}

app/templates/app/menu.html
{% extends "app/base.html" %}
{% load static %}

{% block titulo %}
TFS - Menu
{% endblock %}

{% block contenido %}
  <div class="row">
       <!-- Pie Chart -->
    <div class="col-xl-12 col-lg-12">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Time recorded in all user projects</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-pie pt-4 pb-2">
            <canvas id="myPieChart"></canvas>
          </div>
          <div class="mt-4 text-center small">
            <span class="mr-2">
              <i class="fas fa-circle text-primary"></i> To Do
            </span>
            <span class="mr-2">
              <i class="fas fa-circle text-success"></i> Progres
            </span>
            <span class="mr-2">
              <i class="fas fa-circle text-info"></i> Done
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
  // Set new default font family and font color to mimic Bootstrap's default styling
$(document).ready(function(){
	Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
	Chart.defaults.global.defaultFontColor = '#858796';

	// Pie Chart Example
	var ctx = document.getElementById("myPieChart");
	var myPieChart = new Chart(ctx, {
	  type: 'doughnut',
	  data: {
		labels: ["To DO", "Progres", "Done"],
		datasets: [{
		  data: [ {{lista_tarea}},
              {{lista_trabajado}},
              {{lista_restante}}],
		  backgroundColor: ['#4e73df', '#1cc88a', '#36b9cc'],
		  hoverBackgroundColor: ['#2e59d9', '#17a673', '#2c9faf'],
		  hoverBorderColor: "rgba(234, 236, 244, 1)",
		}],
	  },
	  options: {
		maintainAspectRatio: false,
		tooltips: {
		  backgroundColor: "rgb(255,255,255)",
		  bodyFontColor: "#858796",
		  borderColor: '#dddfeb',
		  borderWidth: 1,
		  xPadding: 15,
		  yPadding: 15,
		  displayColors: false,
		  caretPadding: 10,
		},
		legend: {
		  display: false
		},
		cutoutPercentage: 80,
	  },
	});
});
  </script>
{% endblock %}

app/templates/app/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Register</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'app/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                 {% if messages %}
                      {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{message.tags}}{%endif%} alert-dismissible fade show" role="alert">
                            {{message}}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                      {% endfor %}
                  {% endif %}
              </div>
              <form class="user needs-validation" action="{% url 'app:registrar' %}" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" name="FirstName" placeholder="First Name" required>
                    <div class="valid-feedback"></div>
                    <div class="invalid-feedback">Please choose a FirstName.</div>
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" name="LastName" placeholder="Last Name" required>
                    <div class="valid-feedback"></div>
                    <div class="invalid-feedback">Please choose a LastName.</div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="email" class="form-control form-control-user" id="exampleInputEmail" name="Email" placeholder="Email Address" required>
                    <div class="valid-feedback"></div>
                    <div class="invalid-feedback">Please choose a Email.</div>
                    </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleUsuario" name="Username" placeholder="Usuario" required>
                    <div class="valid-feedback"></div>
                    <div class="invalid-feedback">Please choose a Usuario.</div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" name="Password" placeholder="Password" required>
                    <div class="valid-feedback"></div>
                    <div class="invalid-feedback">Please choose a Password.</div>
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" name="RepeatPassword" placeholder="Repeat Password" required>
                    <div class="valid-feedback"></div>
                    <div class="invalid-feedback">Please choose a RepeatPassword.</div>
                  </div>
                </div>
                <div class="form-group row">
                  <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="CustomSelect" required>
                    <option value="" selected>select rol</option>
                    <option value="Developer">Developer</option>
                    <option value="productowner">Product Owner</option>
                  </select>
                  <div class="invalid-feedback">invalid rol selection</div>
                </div>
                <button class="btn btn-primary btn-user btn-block" type="submit">
                  Register Account
                </button>                
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="{% url 'app:index' %}">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'app/js/sb-admin-2.min.js' %}"></script>
  <script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
      'use strict';
      window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
          form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
              event.preventDefault();
              event.stopPropagation();
            }
            form.classList.add('was-validated');
          }, false);
        });
      }, false);
    })();
  </script>
</body>

</html>